/** Internal routes — use these instead of external bayareadiscoverymuseum.org navigation URLs */
export const routes = {
  home: '/',
  tickets: '/plan-your-visit/',
  membership: '/membership/',
  discoveryZones: '/discovery-zones/',
  events: '/events/',
  programs: '/programs/',
  summerCamps: '/programs/summer-camps/',
  schoolYearCamps: '/programs/school-year-camps/',
  buildACamp: '/programs/school-year-camps/build-a-camp/',
  campRegistration: '/programs/camp-registration/',
  summerBirthdays: '/summer-birthdays/',
  give: '/give/',
  contact: '/contact/',
  workshopsAtYourSite: '/school-community/workshops-at-your-site/',
  workshopsAtMuseum: '/school-community/workshops-at-the-museum/',
  thinkMakeTryToolkit: '/school-community/resources/think-make-try-toolkit/',
  resources: '/school-community/resources/',
  bubbleBash: '/bubble-bash/',
  pride: '/events/pride/',
  goblinJamboree: '/events/goblin-jamboree/',
  privacyPolicy: '/privacy-policy/',
  membershipJoin: '/membership/join/',
  search: '/search/',
} as const;
